host: '192.168.50.140'
user: 'ntucms'
password: '9ol.1qaz5tgb'
port: 22

boardtype: HD # available opts : HD / LD
boardID: Test
hexacontrollerIP: '192.168.50.152'


testCMD:
  cmd: 'echo TESTETTSEESTGESTESTESTETESTETESTSETESTESTESTSETES'
  type: 'waiting_for_job_ended' # waiting_for_job_ended or no_waiting
  delay: 2.0
runCMD:
  cmd: 'sh runGUI.sh {boardtype} {boardID} {hexacontrollerIP} 2>&1 '
  type: 'waiting_for_job_ended'
  delay: 2.0
stopCMD:
  #cmd: 'none'
  type: 'abort_current_ssh_session'
  delay: 0.5
destroyCMD:
  cmd: 'exit' # do nothing
  type: 'waiting_for_job_ended'
  delay: 1.0
