host: '192.168.50.152'
user: 'root'
password: 'centos'
port: 22

firmware_script: 'turnOn_FW_V3.sh'




testCMD:
  cmd: 'echo hiii; ls '
  type: 'waiting_for_job_ended'
  delay: 0.2
runCMD:
  cmd: 'source insmod.sh && cd ~/hgcal_daq && ./{firmware_script} 2>&1'
  type: 'waiting_for_job_ended'
  delay: 1.0
stopCMD:
  cmd: 'systemctl restart daq-server.service ; systemctl restart i2c-server.service'
  type: 'waiting_for_job_ended'
  delay: 0.1
destroyCMD:
  cmd: 'cd ~/hgcal_daq && ./turnOff.sh && exit'
  type: 'waiting_for_job_ended'
  delay: 3.0
