host: '192.168.50.140'
user: 'ntucms'
password: '9ol.1qaz5tgb'
port: 22



testCMD:
  cmd: 'echo TESTETTSEESTGESTESTESTETESTETESTSETESTESTESTSETES'
  type: 'waiting_for_job_ended' # waiting_for_job_ended or no_waiting
  delay: 2.0
runCMD:
  cmd: 'daq-client 2>&1'
  type: 'read_status' # not implemented
  delay: 0.5 
stopCMD:
  cmd: 'none'
  type: 'waiting_for_job_ended'
  delay: 0.1

destroyCMD:
  cmd: 'kill % && exit' # kill daq-client at background and exit
  type: 'waiting_for_job_ended'
  delay: 1.0

