client:
  hw_type: LD
  outputDirectory: /home/ntucms/electronic_test_kria/HD_bottom/data/mytest/pedestal_run/run_20250310_142049/
  run_type: pedestal_run
  serverIP: 192.168.50.180
  zmqPushPull_port: 8888
daq:
  active_menu: randomL1A
  elinks_daq:
  - idcode: 0
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 1
  - idcode: 4
    name: link2
    polarity: 1
  - idcode: 5
    name: link3
    polarity: 1
  - idcode: 40
    name: link4
    polarity: 1
  - idcode: 41
    name: link5
    polarity: 1
  - idcode: 44
    name: link6
    polarity: 1
  - idcode: 45
    name: link7
    polarity: 1
  elinks_trg:
  - idcode: 4
    name: link0
    polarity: 1
  - idcode: 1
    name: link1
    polarity: 1
  - idcode: 0
    name: link2
    polarity: 1
  - idcode: 5
    name: link3
    polarity: 1
  - idcode: 40
    name: link4
    polarity: 1
  - idcode: 41
    name: link5
    polarity: 1
  - idcode: 44
    name: link6
    polarity: 1
  - idcode: 45
    name: link7
    polarity: 1
  elinks_trg_phase:
  - idcode: 1
    name: link0
    polarity: 1
  l1aOffsetFinder:
    L1A_offset_or_BX: 10
    fifo_latency: 0
    method: automatic
  menus:
    calibAndL1A:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      repeatOffset: 200
    calibAndL1AplusTPG:
      NEvents: 1000
      bxCalib: 10
      bxL1A: 33
      lengthCalib: 1
      lengthL1A: 1
      prescale: 0
      trg_fifo_latency: 3
    delayScan:
      acquireLength: 1000
      delayStep: 1
      idlePattern: 0XACCCCCCC
      maxDelay: 512
    externalL1A:
      NEvents: 10000
      bxCalibExt: 10
      lengthCalibExt: 2
      loopBack: true
      prescale: 0
      trg_fifo_latency: 3
      trgphase_fifo_latency: 15
    marsCalibAndL1A:
      bxCalib: 10
      bxL1A: 45
      prescale: 0
      repeatOffset: 200
    marsRndL1A:
      bx_min: 45
      log2_rand_bx_period: 10
    randomL1A:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 0
    randomL1AplusTPG:
      NEvents: 10000
      bx_min: 45
      log2_rand_bx_period: 10
      trg_fifo_latency: 3
  zmqPushPull_port: 8888
roc_s0_0:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
        SelTC4: 0
      1:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
        SelTC4: 0
    GlobalAnalog:
      0:
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        dac_pol: 0
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
      1:
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        dac_pol: 0
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
    ReferenceVoltage:
      0:
        Inv_vref: 400
        Noinv_vref: 250
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 1023
        Vbg_1v: 3
      1:
        Inv_vref: 400
        Noinv_vref: 250
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 1023
        Vbg_1v: 3
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        EdgeSel_T1: 1
        RunL: 1
        RunR: 1
        in_inv_cmd_rx: 0
roc_s0_1:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
        SelTC4: 0
      1:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
        SelTC4: 0
    GlobalAnalog:
      0:
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        dac_pol: 0
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
      1:
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        dac_pol: 0
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
    ReferenceVoltage:
      0:
        Inv_vref: 400
        Noinv_vref: 250
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 1023
        Vbg_1v: 3
      1:
        Inv_vref: 400
        Noinv_vref: 250
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 1023
        Vbg_1v: 3
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        EdgeSel_T1: 1
        RunL: 1
        RunR: 1
        in_inv_cmd_rx: 0
roc_s1_0:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
        SelTC4: 0
      1:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
        SelTC4: 0
    GlobalAnalog:
      0:
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        dac_pol: 0
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
      1:
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        dac_pol: 0
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
    ReferenceVoltage:
      0:
        Inv_vref: 400
        Noinv_vref: 250
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 1023
        Vbg_1v: 3
      1:
        Inv_vref: 400
        Noinv_vref: 250
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 1023
        Vbg_1v: 3
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        EdgeSel_T1: 1
        RunL: 1
        RunR: 1
        in_inv_cmd_rx: 0
roc_s1_1:
  sc:
    DigitalHalf:
      0:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
        SelTC4: 0
      1:
        Bx_offset: 2
        CalibrationSC: 1
        IdleFrame: 214748364
        L1Offset: 10
        SelTC4: 0
    GlobalAnalog:
      0:
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        dac_pol: 0
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
      1:
        Delay40: 2
        Delay65: 3
        Delay87: 3
        Delay9: 3
        Ibi_inv_buf: 0
        Ibi_noinv_buf: 0
        Ibo_inv_buf: 12
        Ibo_noinv_buf: 12
        dac_pol: 0
        range_inv: 6
        range_tot: 7
        trim_vbi_pa: 15
    MasterTdc:
      0:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
      1:
        BIAS_CAL_DAC_CTDC_P_D: 2
        BIAS_CAL_DAC_CTDC_P_EN: 1
        BIAS_FOLLOWER_CAL_P_CTDC_EN: 1
        BIAS_FOLLOWER_CAL_P_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_D: 4
        BIAS_FOLLOWER_CAL_P_FTDC_EN: 1
        BIAS_I_CTDC_D: 10
        BIAS_I_FTDC_D: 10
        CTDC_CALIB_FREQUENCY: 2
        FOLLOWER_CTDC_EN: 1
        FOLLOWER_FTDC_EN: 1
        FTDC_CALIB_FREQUENCY: 2
        GLOBAL_EN_BUFFER_CTDC: 1
        GLOBAL_EN_BUFFER_FTDC: 1
    ReferenceVoltage:
      0:
        Inv_vref: 400
        Noinv_vref: 250
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 1023
        Vbg_1v: 3
      1:
        Inv_vref: 400
        Noinv_vref: 250
        Refi: 1
        Toa_vref: 1023
        Tot_vref: 1023
        Vbg_1v: 3
    Top:
      0:
        BIAS_I_PLL_D: 63
        EN_HIGH_CAPA: 1
        EdgeSel_T1: 1
        RunL: 1
        RunR: 1
        in_inv_cmd_rx: 0
